import type { Metadata } from "next";
import { Geist, Geist_Mono, Source_Serif_4 } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Closest free lookalike to Minion Pro — classic book serif, similar proportions.
// (Previously tried Fraunces, EB Garamond, and Playfair Display — Playfair was
// the closest runner-up if this doesn't land either.)
const sourceSerif = Source_Serif_4({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["600", "700", "800"],
});

export const metadata: Metadata = {
  title: "MusicEXL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${sourceSerif.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <script dangerouslySetInnerHTML={{ __html: `
          if (typeof URL.parse !== 'function') {
            URL.parse = function(url, base) {
              try { return new URL(url, base); } catch { return null; }
            };
          }
        `}} />
        {children}
      </body>
    </html>
  );
}
